"""substitui localizacao por dimensoes do item

Revision ID: 0876953b3b91
Revises: 9197c43e2842
Create Date: 2026-09-12 19:44:40.841740
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0876953b3b91'
down_revision: Union[str, None] = '9197c43e2842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('items', sa.Column('width_cm', sa.Numeric(precision=8, scale=2), nullable=True))
    op.drop_column('items', 'longitude')
    op.drop_column('items', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.drop_column('items', 'width_cm')
    op.drop_column('items', 'height_cm')
    # ### end Alembic commands ###
